name: Build release

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

permissions:
  contents: write

# Set MOAT_VERSION environment variable
env:
  MOAT_VERSION: ${{ github.ref_name }}

jobs:
  build:
    name: GoReleaser Build
    runs-on: ubuntu-latest

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set Up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.x"

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v7
        with:
          distribution: goreleaser
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
